=== lwchkg/dfend-x/src/Tools/CheatsServer/Cheats.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT CheatDB (GameRecord)+>
<!ATTLIST CheatDB
	Version CDATA #IMPLIED
>

<!ELEMENT GameRecord (Action)+>
<!ATTLIST GameRecord
	Name CDATA #REQUIRED
>

<!ELEMENT Action (ChangeAddress | ChangeAddressWithDialog | Internal)+>
<!ATTLIST Action
	Name CDATA #REQUIRED
	FileMask CDATA #REQUIRED
>

<!ELEMENT ChangeAddress EMPTY>
<!ATTLIST ChangeAddress
	Addresses CDATA #REQUIRED
	Bytes CDATA #REQUIRED
	NewValue CDATA #REQUIRED
>

<!ELEMENT ChangeAddressWithDialog EMPTY>
<!ATTLIST ChangeAddressWithDialog
	Addresses CDATA #REQUIRED
	Bytes CDATA #REQUIRED
	DefaultValue CDATA #IMPLIED
	DefaultValueAddress CDATA #IMPLIED
	Prompt CDATA #IMPLIED
	MinValue CDATA #IMPLIED
	MaxValue CDATA #IMPLIED
>

<!ELEMENT Internal EMPTY>
<!ATTLIST Internal
	Nr CDATA #REQUIRED
>

=== lwchkg/dfend-x/src/Bin/Cheats.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE CheatDB SYSTEM "http://dfendreloaded.sourceforge.net/Packages/Cheats.dtd">
<CheatDB Version="2">
  <GameRecord Name="Dark Side of Xeen">
    <Action Name="Money" FileMask="DARK??.SAV">
      <ChangeAddress Addresses="$39FB;$39FF;$3A03;$3A07" Bytes="4" NewValue="$FFFFFFFF"/>
    </Action>
    <Action Name="Level" FileMask="DARK??.SAV">
      <ChangeAddress Addresses="3605;3607;3609;3611;3613;3615;3617;3620;3959;3961;3963;3965;3967;3969;3971;3974;4313;4315;4317;4319;4321;4323;4325;4328;4667;4669;4671;4673;4675;4677;4679;4682;5021;5023;5025;5027;5029;5031;5033;5036;5375;5377;5379;5381;5383;5385;5387;5390;5729;5731;5733;5735;5737;5739;5741;5744;6083;6085;6087;6089;6091;6093;6095;6098;6437;6439;6441;6443;6445;6447;6449;6452;6791;6793;6795;6797;6799;6801;6803;6806;7145;7147;7149;7151;7153;7155;7157;7160;7499;7501;7503;7505;7507;7509;7511;7514;7853;7855;7857;7859;7861;7863;7865;7868;8207;8209;8211;8213;8215;8217;8219;8222;8561;8563;8565;8567;8569;8571;8573;8576;8915;8917;8919;8921;8923;8925;8927;8930;9269;9271;9273;9275;9277;9279;9281;9284;9623;9625;9627;9629;9631;9633;9635;9638;9977;9979;9981;9983;9985;9987;9989;9992;10331;10333;10335;10337;10339;10341;10343;10346;10685;10687;10689;10691;10693;10695;10697;10700;11039;11041;11043;11045;11047;11049;11051;11054;11393;11395;11397;11399;11401;11403;11405;11408;11747;11749;11751;11753;11755;11757;11759;11762;12101;12103;12105;12107;12109;12111;12113;12116;12455;12457;12459;12461;12463;12465;12467;12470;12809;12811;12813;12815;12817;12819;12821;12824;13163;13165;13167;13169;13171;13173;13175;13178;13517;13519;13521;13523;13525;13527;13529;13532;13871;13873;13875;13877;13879;13881;13883;13886" Bytes="2" NewValue="$FFFF"/>
    </Action>
    <Action Name="Position" FileMask="DARK??.SAV">
      <Internal Nr="1"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Dune 2">
    <Action Name="Harkonnen" FileMask="_SAVE???.DAT">
      <ChangeAddress Addresses="$186" Bytes="2" NewValue="64000"/>
    </Action>
    <Action Name="Ordos" FileMask="_SAVE???.DAT">
      <ChangeAddress Addresses="$1C8" Bytes="2" NewValue="64000"/>
    </Action>
    <Action Name="Artreidis" FileMask="_SAVE???.DAT">
      <ChangeAddress Addresses="$1C8" Bytes="2" NewValue="64000"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Privateer">
    <Action Name="Money" FileMask="*.SAV">
      <Internal Nr="2"/>
    </Action>
    <Action Name="Ship" FileMask="*.SAV">
      <Internal Nr="7"/>
    </Action>
    <Action Name="Position" FileMask="*.SAV">
      <Internal Nr="8"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Rings of Medusa">
    <Action Name="Money" FileMask="*.ROM">
      <ChangeAddress Addresses="$3BC7;$3BC8;$3BC9" Bytes="1" NewValue="$FF"/>
      <ChangeAddress Addresses="$3BCA" Bytes="1" NewValue="$6F"/>
    </Action>
    <Action Name="Army" FileMask="*.ROM">
      <ChangeAddress Addresses="$A0E;$A0F;$A10;$A12;$A13;$A14;$A16;$A17;$A18;$A1A;$A1B;$A1C;$A1E;$A1F;$A20;$A22;$A23;$A24;$A26;$A27;$A28" Bytes="1" NewValue="$FF"/>
      <ChangeAddress Addresses="$9BA" Bytes="1" NewValue="$F9"/>
      <ChangeAddress Addresses="$9BB;$9BC" Bytes="1" NewValue="$FF"/>
      <ChangeAddress Addresses="$9BD" Bytes="1" NewValue="$06"/>
    </Action>
  </GameRecord>
  <GameRecord Name="SimCity 2000">
    <Action Name="Money" FileMask="*.SC2">
      <Internal Nr="3"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Tie-Fighter">
    <Action Name="Points" FileMask="*.TFR">
      <ChangeAddressWithDialog Addresses="$4" Bytes="2" DefaultValueAddress="$4" Prompt="Points (0-65535)"/>
    </Action>
    <Action Name="Experience" FileMask="*.TFR">
      <ChangeAddressWithDialog Addresses="$8" Bytes="2" DefaultValueAddress="$8" Prompt="Experience (0-65535)"/>
    </Action>
    <Action Name="Rang" FileMask="*.TFR">
      <ChangeAddressWithDialog Addresses="$2" Bytes="1" DefaultValueAddress="$2" Prompt="Rang (0=Cadet, 1=Officer, 2=Leutnant, 3=Captain, 4=Commander, 5=General)" MaxValue="5"/>
    </Action>
    <Action Name="All battles" FileMask="*.TFR">
      <ChangeAddress Addresses="$268" Bytes="1" NewValue="9"/>
      <ChangeAddress Addresses="$269;$26A;$26B;$26C;$26D;$26E;$26F" Bytes="1" NewValue="3"/>
      <ChangeAddress Addresses="$27E" Bytes="1" NewValue="5"/>
      <ChangeAddress Addresses="$27F" Bytes="1" NewValue="4"/>
      <ChangeAddress Addresses="$280;$281" Bytes="1" NewValue="5"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Patrizier">
    <Action Name="Money" FileMask="*.PSD">
      <ChangeAddress Addresses="$213;$214;$215" Bytes="1" NewValue="255"/>
      <ChangeAddress Addresses="$216" Bytes="1" NewValue="100"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Ultima 8">
    <Action Name="Cheatmode" FileMask="AVATAR.*">
      <ChangeAddress Addresses="$2A;$2B" Bytes="1" NewValue="1"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Betrayal at Krondor">
    <Action Name="Money" FileMask="*.GAM">
      <ChangeAddress Addresses="$66" Bytes="4" NewValue="$6FFFFF"/>
    </Action>
    <Action Name="Characters" FileMask="*.GAM">
      <Internal Nr="4"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Strike Commander TO1">
    <Action Name="Money" FileMask="*.TO1">
      <ChangeAddress Addresses="$191;$18D" Bytes="2" NewValue="0"/>
      <ChangeAddress Addresses="$18A" Bytes="1" NewValue="255"/>
      <ChangeAddress Addresses="$18B" Bytes="1" NewValue="$5F"/>
    </Action>
    <Action Name="Weapons" FileMask="*.TO1">
      <ChangeAddress Addresses="$16F;$171;$173;$175;$177;$179;$17B;$17D;$17F" Bytes="1" NewValue="255"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Advanted Tennis">
    <Action Name="Parameter" FileMask="*.PLY">
      <Internal Nr="5"/>
    </Action>
  </GameRecord>
  <GameRecord Name="SimCity">
    <Action Name="Money" FileMask="*.CTY">
      <ChangeAddress Addresses="$C24" Bytes="1" NewValue="$5F"/>
      <ChangeAddress Addresses="$C25;$C26;$C27" Bytes="1" NewValue="255"/>
    </Action>
  </GameRecord>
  <GameRecord Name="Das Schwarze Auge">
    <Action Name="Characters/Money" FileMask="*.CHR">
      <ChangeAddress Addresses="$1C" Bytes="2" NewValue="$FFFF"/>
    </Action>
    <Action Name="Characters/Properties" FileMask="*.CHR">
      <ChangeAddress Addresses="$24;$25;$27;$28;$2A;$2B;$2D;$2E;$30;$31;$33;$34;$36;$37" Bytes="1" NewValue="18"/>
      <ChangeAddress Addresses="$39;$3A;$3C;$3D;$3F;$40;$42;$43;$45;$46;$48;$49;$4B;$4C" Bytes="1" NewValue="2"/>
    </Action>
    <Action Name="Characters/Life energy" FileMask="*.CHR">
      <ChangeAddressWithDialog Addresses="$4E,$50" Bytes="1" DefaultValue="99" Prompt="Life energy (0-99)" MaxValue="99"/>
    </Action>
    <Action Name="Characters/Astral energy" FileMask="*.CHR">
      <ChangeAddressWithDialog Addresses="$4E,$50" Bytes="1" DefaultValue="99" Prompt="Astral energy (0-99)" MaxValue="99"/>
    </Action>
    <Action Name="Characters/Talents" FileMask="*.CHR">
      <ChangeAddress Addresses="$0F8;$0F9;$0FA;$0FB;$0FC;$0FD;$0FE;$0FF;$100;$101;$102;$103;$104;$105;$106;$107;$108;$109;$10A;$10B;$10C;$10D;$10E;$10F;$110;$111;$112;$113;$114;$115;$116;$117;$118;$119;$11A;$11B;$11C;$11D;$11E;$11F;$120;$121;$122;$123;$124;$125;$126;$127;$128;$129;$12A;$12B" Bytes="1" NewValue="18"/>
    </Action>
    <Action Name="Characters/Magic power" FileMask="*.CHR">
      <ChangeAddress Addresses="$12E;$12F;$130;$131;$132;$133;$134;$135;$136;$137;$138;$139;$13A;$13B;$13C;$13D;$13E;$13F;$140;$141;$142;$143;$144;$145;$146;$147;$148;$149;$14A;$14B;$14C;$14D;$14E;$14F;$150;$151;$152;$153;$154;$155;$156;$157;$158;$159;$15A;$15B;$15C;$15D;$15E;$15F;$160;$161;$162;$163;$164;$165;$166;$167;$168;$169;$16A;$16B;$16C;$16D;$16E;$16F;$170;$171;$172;$173;$174;$175;$176;$177;$178;$179;$17A;$17B;$17C;$17D;$17E;$17F;$180;$181;$182;$183" Bytes="1" NewValue="18"/>
    </Action>
    <Action Name="Characters/Experience points" FileMask="*.CHR">
      <ChangeAddressWithDialog Addresses="$18" Bytes="4" DefaultValue="1500" Prompt="Experience (0-1500)" MinValue="0" MaxValue="1500"/>
    </Action>
    <Action Name="Characters/Body size" FileMask="*.CHR">
      <ChangeAddressWithDialog Addresses="$13" Bytes="1" DefaultValue="250" Prompt="Body size (1-255)" MinValue="1"/>
    </Action>
    <Action Name="Characters/Level" FileMask="*.CHR">
      <ChangeAddressWithDialog Addresses="$17" Bytes="1" DefaultValue="10" Prompt="Level (0-255)"/>
    </Action>
    <Action Name="Characters/Attack/Parade" FileMask="*.CHR">
      <ChangeAddressWithDialog Addresses="$57,$58,$59,$5A,$5B,$5C,$5D,$5E,$5F,$60,$61,$62,$63,$64,$65" Bytes="1" DefaultValue="12" Prompt="AT/PA (0-127)" MaxValue="127"/>
    </Action>
    <Action Name="Saved games/Money" FileMask="SPIEL_?_.">
      <ChangeAddress Addresses="-$28A0;-$21D6;-$1B0C;-$1442;-$0D78;-$06AE" Bytes="2" NewValue="$FFFF"/>
    </Action>
    <Action Name="Saved games/Properties" FileMask="SPIEL_?_.">
      <ChangeAddress Addresses="-$2898;-$2897;-$2895;-$2894;-$2892;-$2891;-$288F;-$288E;-$288C;-$288B;-$2889;-$2888;-$2886;-$2885;-$21CE;-$21CD;-$21CB;-$21CA;-$21C8;-$21C7;-$21C5;-$21C4;-$21C2;-$21C1;-$21BF;-$21BE;-$21BC;-$21BB;-$1B04;-$1B03;-$1B01;-$1B00;-$1AFE;-$1AFD;-$1AFB;-$1AFA;-$1AF8;-$1AF7;-$1AF5;-$1AF4;-$1AF2;-$1AF1;-$143A;-$1439;-$1437;-$1436;-$1434;-$1433;-$1431;-$1430;-$142E;-$142D;-$142B;-$142A;-$1428;-$1427;-$0D70;-$0D6F;-$0D6D;-$0D6C;-$0D6A;-$0D69;-$0D67;-$0D66;-$0D64;-$0D63;-$0D61;-$0D60;-$0D5E;-$0D5D;-$06A6;-$06A5;-$06A3;-$06A2;-$06A0;-$069F;-$069D;-$069C;-$069A;-$0699;-$0697;-$0696;-$0694;-$0693" Bytes="1" NewValue="127"/>
