=== lwchkg/dfend-x/src/Tools/DataReaderServer/DataReader.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT DataReader (GamesList | GamePage | CoverPage)+>
<!ATTLIST DataReader
	Version CDATA #REQUIRED
>

<!ELEMENT GamesList (Element | PerGameBlock)+>
<!ATTLIST GamesList
	URL CDATA #REQUIRED
	AllPlatformsURL CDATA #IMPLIED
>

<!ELEMENT GamePage (Element)>
<!ATTLIST GamePage
	URL CDATA #REQUIRED
>

<!ELEMENT CoverPage (Element | Javascript)+>
<!ATTLIST CoverPage
	URL CDATA #REQUIRED
>

<!ELEMENT Element (Element | PerGameBlock | Link | SearchGameData | Img | Javascript)+>
<!ATTLIST Element
  Type CDATA #IMPLIED
  Key CDATA #IMPLIED
  Value CDATA #IMPLIED
  Nr CDATA #IMPLIED
  ContainsText CDATA #IMPLIED
>

<!ELEMENT PerGameBlock (Element | PerGameBlock | Link)+>
<!ATTLIST PerGameBlock
  Type CDATA #IMPLIED
  Key CDATA #IMPLIED
  Value CDATA #IMPLIED
>

<!ELEMENT Link EMPTY>
<!ATTLIST Link
	Nr CDATA #IMPLIED
	HrefSubstring CDATA #REQUIRED
>

<!ELEMENT Javascript EMPTY>
<!ATTLIST Javascript
  ContainsText CDATA #IMPLIED
>

<!ELEMENT SearchGameData EMPTY>
<!ATTLIST SearchGameData
	Publisher CDATA #IMPLIED
	Developer CDATA #IMPLIED
	Year CDATA #IMPLIED
	Genre CDATA #IMPLIED
	IgnoreTags CDATA #IMPLIED
	StartTokens CDATA #IMPLIED
	StoppTokens CDATA #IMPLIED
>

<!ELEMENT Img EMPTY>

=== lwchkg/dfend-x/src/Tools/DataReaderServer/DataReader.v4.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE DataReader SYSTEM "http://dfendreloaded.sourceforge.net/DataReader/DataReader.dtd">

<DataReader Version="4">

  <GamesList URL="http://www.mobygames.com/search/quick/q,%s/sFilter,1/sG,1/" AllPlatformsURL="http://www.mobygames.com/search/quick/q,%s/sFilter,1/sG,1/">
    <Element Type="div" Key="class" Value="results clear mb40">
      <PerGameBlock Type="div" Key="class" Value="list-info ">
        <Element Type="h3" Key="class" Value="list">
          <Link  HrefSubstring="/game/" />
        </Element>
      </PerGameBlock>
    </Element>
  </GamesList>

  <GamePage URL="http://www.mobygames.com">
    <Element Type="div" Key="id" Value="main">

	  <Element Type="div" Key="class" Value="game-nav">
	    <Element Type="div" Key="class" Value="text-center">

		</Element>
	  </Element>

      <Element Type="div" Key="class" Value="game-info">
	    <Element Type="div" Key="class" Value="detail">
	      <Element Type="div" Key="class" Value="listings">
            <SearchGameData Publisher="Published by" Developer="Developed by" Year="Released" Genre="Genre" />
		  </Element>
	    </Element>
	  </Element>
	  
	</Element>
  </GamePage>	
  
  <CoverPage URL="http://www.mobygames.com">
    <Element Type="div" Key="class" Value="rightPanelMain">
	  <Img Type="class" Value="big-shot" />
	</Element>
  </CoverPage>

</DataReader>

=== lwchkg/dfend-x/src/Tools/DataReaderServer/DataReader.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE DataReader SYSTEM "http://dfendreloaded.sourceforge.net/DataReader/DataReader.dtd">

<DataReader Version="10">

  <GamesList URL="http://www.mobygames.com/search/quick/q,%s/sFilter,1/sG,1/p,2/" AllPlatformsURL="http://www.mobygames.com/search/quick/q,%s/sFilter,1/sG,1/">
    <Element Type="div" Key="id" Value="searchResults">
      <PerGameBlock Type="div" Key="class" Value="searchResult">
        <Element Type="div" Key="class" Value="searchTitle">
          <Link  HrefSubstring="/game/" />
        </Element>
      </PerGameBlock>
    </Element>
  </GamesList>

  <GamePage URL="http://www.mobygames.com">
  
    <Element Type="div" Key="id" Value="wrapper">
    <Element Type="div" Key="class" Value="container">
  
    <Element Type="div" Key="class" Value="col-md-12 col-lg-12">  
      <Element Type="div" Key="id" Value="floatholder coreGameInfo">
        <Element Type="table">
          <Element Type="div" Key="id" Value="coreGameCover">
            <Link/>
          </Element>
          <Element Type="div" Key="id" Value="coreGameRelease">
            <SearchGameData Publisher="Published by" Developer="Developed by" Year="Released" />
          </Element>
          <Element Type="div" Key="id" Value="coreGameGenre">
            <SearchGameData Genre="Genre" />
          </Element>
        </Element>		
      </Element>
	</Element>
	<Element Type="div" Key="class" Value="col-md-8 col-lg-8">
	  <SearchGameData Notes="Notes" StartTokens="Description" StoppTokens="edit description;Screenshots;Alternate Titles;Part of the Following Groups;User Reviews"/>
	</Element>
	
	</Element>
	</Element>
	
  </GamePage>
  
  <CoverPage URL="http://www.mobygames.com">
    <Element Type="div" Key="id" Value="wrapper">
    <Element Type="div" Key="class" Value="container">
	  <Img/>
	</Element>
	</Element>
  </CoverPage>

</DataReader>

=== lwchkg/dfend-x/src/Tools/DataReaderServer/DataReader.v6.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE DataReader SYSTEM "http://dfendreloaded.sourceforge.net/DataReader/DataReader.dtd">

<DataReader Version="6">

  <GamesList URL="http://www.mobygames.com/search/quick/q,%s/sFilter,1/sG,1/p,2/" AllPlatformsURL="http://www.mobygames.com/search/quick/q,%s/sFilter,1/sG,1/">
    <Element Type="div" Key="class" Value="results clear mb40">
      <PerGameBlock Type="h3" Key="class" Value="list">
        <Link  HrefSubstring="/game/" />
      </PerGameBlock>
    </Element>
  </GamesList>

  <GamePage URL="http://www.mobygames.com">
    <Element Type="div" Key="id" Value="main">

	  <Element Type="div" Key="class" Value="game-nav">
	    <Element Type="div" Key="class" Value="text-center">
		  <Link />
		</Element>
	  </Element>

      <Element Type="div" Key="class" Value="game-info">
	    <Element Type="div" Key="class" Value="detail">
	      <Element Type="div" Key="class" Value="listings">
            <SearchGameData Publisher="Published by" Developer="Developed by" Year="Released" Genre="Genre" />
		  </Element>
		  <SearchGameData Notes="SELF" />
	    </Element>
	  </Element>
	  
	</Element>
  </GamePage>	
  
  <CoverPage URL="http://www.mobygames.com">
    <Javascript ContainsText="var screenshots = {" />
  </CoverPage>

</DataReader>
